# docker-compose up -d
# docker exec -it solace cli -A
version: "3.9"

services:
  solace:
    image: solace/solace-pubsub-standard:latest
    shm_size: 2g
    ulimits:
      nofile:
        soft: 2448
        hard: 38048
    ports:
      #Port Mappings:  Ports are mapped straight through from host to
      #container.  This may result in port collisions on commonly used
      #ports that will cause failure of the container to start.
      #Web transport
      - "8008:8008"
      #REST Default VPN
      - "9000:9000"
      #MQTT Default VPN
      - 1883:1883
      #MQTT Default VPN over WebSockets
      - 8000:8000
      #SEMP / PubSub+ Manager
      - "8080:8080"
      #SMF Port 55555 in use on Mac OS Big Sur
      - "44444:55555"
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=1000

  curl:
    image: curlimages/curl
    environment:
      - solace_admin_url=http://solace:8080
      - solace_health_check_url=http://solace:5550/health-check/guaranteed-active
    volumes:
      - ./wait-for-solace-ready.sh:/wait-for-solace-ready.sh
      - ./provision.sh:/provision.sh
    command: sh -c 'sh /wait-for-solace-ready.sh && sh /provision.sh'
    depends_on:
      - solace
